name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
      # TODO: Convert this to a Gemfile when we have multiple/versioned dependencies.
      - name: Install dependencies
        run: gem install rspec rubocop
      - name: Run spec
        run: rspec
